apiVersion: v1
kind: ConfigMap
metadata:
  name: zaf-tester-cm-env
data:
  ZAIRFLOW_GIT_AUTOSYNC_URI: 'https://github.com/LamaAni/KubernetesJobOperator.git'
  ZAIRFLOW_DAGS_SUBFOLDER: 'examples/dags'
  AIRFLOW__CORE__LOGGING_CONFIG_CLASS: airflow_db_logger.airflow_log_config.LOGGING_CONFIG
---
apiVersion: v1
kind: Pod
metadata:
  name: zaf-tester
  labels:
    name: zaf-tester
spec:
  volumes:
    - name: dag-sync
      emptyDir: {}
    - name: log-sync
      emptyDir: {}
  containers:
    - name: airflow-webserver
      image: 'lamaani/zairflow:local'
      imagePullPolicy: 'Never'
      volumeMounts:
        - mountPath: /app
          name: dag-sync
        - mountPath: /airflow/logs
          name: log-sync
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: '1Gi'
          cpu: '500m'
      env:
        - name: ZAIRFLOW_CONTAINER_TYPE
          value: 'webserver'
        - name: ZAIRFLOW_RUN_INITDB
          value: 'true'
      envFrom:
        - configMapRef:
            name: zaf-tester-cm-env
    - name: airflow-scheduler
      image: 'lamaani/zairflow:local'
      imagePullPolicy: 'Never'
      volumeMounts:
        - mountPath: /app
          name: dag-sync
        - mountPath: /airflow/logs
          name: log-sync
      resources:
        limits:
          memory: '1.5Gi'
          cpu: '500m'
      env:
        - name: ZAIRFLOW_CONTAINER_TYPE
          value: 'scheduler'
        - name: ZAIRFLOW_WAIT_FOR
          value: 'localhost:8080'
      envFrom:
        - configMapRef:
            name: zaf-tester-cm-env
    - name: airflow-postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_DB
          value: airflow
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: MAX_CONNECTIONS
          value: '10000'
      resources:
        limits:
          memory: '200Mi'
          cpu: '150m'
