#!/usr/bin/env bash

: ${REPO_PATH:="$(realpath $(dirname $(realpath "$BASH_SOURCE[0]")))"}

source "$REPO_PATH/docker/scripts/common.sh"

log:sep "Preparing build"

source "$REPO_PATH/envs"
assert $? "Failed to load core enviroment"

log:sep "IMAGE"
source "$REPO_PATH/docker/build" --push

log:sep "Build compleated successfully"
