#!/usr/bin/env bash
: ${REPO_PATH:="$(realpath $(dirname $(realpath "$BASH_SOURCE[0]")))"}
: ${ZAIRFLOW_IMAGE_REPOSITORY:="lamaani/zairflow"}
: ${ZAIRFLOW_VERSION:="0.3"}

if [ -z "$ZAIRFLOW_VERSION_PATCH" ]; then
    ZAIRFLOW_VERSION_PATCH=0
    if [ -f "$REPO_PATH/patch_number" ]; then
        ZAIRFLOW_VERSION_PATCH=$(cat "$REPO_PATH/patch_number")
    fi
fi

: ${ZAIRFLOW_FULL_VERSION:="$ZAIRFLOW_VERSION.$ZAIRFLOW_VERSION_PATCH"}
