apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: testpod
spec:
  containers:
  - name: testpod
    image: lamaani/zairflow:debug-debug_3_8_6
    imagePullPolicy: Always
    command:
        - sleep
        - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
