apiVersion: v1
kind: Service
metadata:
  name: {{ include "zairflow-helm.fullname" . }}-web-svc
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{- .Values.webserver.port -}}
      targetPort: {{- .Values.webserver.port -}}
  clusterIP: None
  selector:
    deployment-target: {{ include "zairflow-helm.fullname" . }}-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zairflow-test-pg
spec:
  selector:
    matchLabels:
      app: zairflow-test-pg # has to match .spec.template.metadata.labels
  serviceName: 'zairflow-test-pg-svc'
  replicas: 1
  template:
    metadata:
      labels:
        app: zairflow-test-pg # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: airflow-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: MAX_CONNECTIONS
              value: '100000'
          resources:
            limits:
              memory: '200Mi'
              cpu: '150m'
