#!/usr/bin/env bash
: ${SCRIPTS_PATH:="$(dirname $(dirname $(realpath "$BASH_SOURCE[0]")))"}
source "$SCRIPTS_PATH/common.sh"

source "$SCRIPTS_PATH/../envs"
: ${ZAIRFLOW_VERSION_PATCH:=0}

ZAIRFLOW_VERSION_PATCH=$((ZAIRFLOW_VERSION_PATCH + 1))
echo "$ZAIRFLOW_VERSION_PATCH" >"$REPO_PATH/patch_number"
assert $? "Failed to advance version patch number." || exit $?
log:info "Advanced patch number to $ZAIRFLOW_VERSION_PATCH"
