{{ $full_name := include "zairflow-helm.fullname" . }}
{{ $running_namespace := include "zairflow-helm.namespace" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $full_name }}-envs
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
data:
  {{- if eq .Values.executor.type "KubernetesExecutor" }}
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: "/airflow/zairflow_worker_pod.yaml"
  ZAIRFLOW_KUBERNETES_EXECUTOR_WORKER_CONFIG: {{ include "zairflow.kubernetes.worker" . | b64enc | quote }}
  {{- end }}

  # Added envs. These will not affect the db operation.
  {{- tuple .Values.envs | include "inject-yaml" | nindent 2 }}
  
  AIRFLOW__CORE__EXECUTOR: "{{ .Values.executor.type }}"

  # Configure if the kubernetes executor
  {{- if eq .Values.executor.type "KubernetesExecutor" }}
  
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: {{ default .Values.image.repository .Values.executor.workerImageRepository }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ default .Values.image.tag .Values.executor.workerImageTag }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: {{ default .Values.image.pullPolicy .Values.executor.workerImagePullPolicy }}
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: "{{ $full_name }}-envs"
  AIRFLOW__KUBERNETES__NAMESPACE: {{ .Values.executor.namespace | default $running_namespace }}
  {{- if .Values.serviceAccount.enabled }}
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "{{ include "zairflow-helm.serviceAccountName" . }}"
  {{- end }}
  {{- end }}

  {{- if .Values.postgres.enabled }}
  ZAIRFLOW_DB_HOST: "{{ $full_name }}-pg-db-svc"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{- .Values.postgres.credentials.user }}:{{- .Values.postgres.credentials.password }}@{{ $full_name }}-pg-db-svc:{{- .Values.postgres.port }}/{{- .Values.postgres.db }}"
  {{- end }}

  {{- tuple .Values.overrideEnvs | include "inject-yaml" | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $full_name }}-kube-worker-envs
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
data:
  GIT_AUTOSYNC_MAX_SYNC_RUN_COUNT: "0"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_MAX_OVERFLOW: "1"
  AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE: "3"
  AIRFLOW__DB_LOGGER__WRITE_TO_SHELL: "true"
  AIRFLOW__DB_LOGGER__PROCESSER_LOG_LEVEL: INFO