{{ $full_name := include "zairflow-helm.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $full_name }}-envs
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
data:
  # Added envs. These will not affect the db operation.
  {{- tuple .Values.envs | include "inject-yaml" | nindent 2 }}
  
  AIRFLOW__CORE__EXECUTOR: "{{ .Values.executor.type }}"

  # Configure if the kubernetes executor
  {{- if eq .Values.executor.type "KubernetesExecutor" }}
  
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: {{ default .Values.image.repository .Values.executor.workerImageRepository }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ default .Values.image.tag .Values.executor.workerImageTag }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: {{ default .Values.image.pullPolicy .Values.executor.workerImagePullPolicy }}
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: "{{ $full_name }}-envs"
  {{- if .Values.serviceAccount.enabled }}
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "{{ include "zairflow-helm.serviceAccountName" . }}"
  {{- end }}
  {{- end }}

  {{- if .Values.postgres.enabled }}
  ZAIRFLOW_DB_HOST: "{{ $full_name }}-pg-db-svc"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{- .Values.postgres.credentials.user }}:{{- .Values.postgres.credentials.password }}@{{ $full_name }}-pg-db-svc:{{- .Values.postgres.port }}/{{- .Values.postgres.db }}"
  {{- end }}

  {{- tuple .Values.overrideEnvs | include "inject-yaml" | nindent 2 }}
