{{- if .Values.init_environment.enabled }}
{{ $full_name := include "zairflow-helm.fullname" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $full_name }}-init-{{ randAlphaNum 5 | lower }}
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # Will try and preform an init_environment and than delete the job.
    {{- if .Values.init_environment.auto_delete }}
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- end }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        deployment-target: {{ $full_name }}-init_environment
        {{- include "zairflow-helm.labels" . | nindent 8 }}
      annotations:
        {{- include "zairflow-helm.metadata_checksums" . | nindent 8 }}
    spec:
      {{- include "zairflow-helm.node_selection_and_toleration" . | nindent 6 }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "zairflow-helm.serviceAccountName" . }}
      {{- end}}
      terminationGracePeriodSeconds: {{ default 10 .Values.init_environment.terminationGracePeriodSeconds }}
      restartPolicy: OnFailure
      containers:
        - name: airflow-init
          image: {{ include "zairflow-helm.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZAIRFLOW_CONTAINER_TYPE
              value: 'init_environment'
            {{- tuple .Values.init_environment.envs | include "inject-yaml" | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ $full_name }}-envs
          resources:
          {{- tuple .Values.init_environment.resources | include "inject-yaml" | nindent 12 }}
        {{- tuple .Values.init_environment.injectContainerYaml | include "inject-yaml" | nindent 10 }}
      {{- tuple .Values.init_environment.containers | include "inject-yaml" | nindent 8 }}
    {{- tuple .Values.init_environment.injectTemplateSpecYaml | include "inject-yaml" | nindent 6 }}
  {{- tuple .Values.init_environment.injectSpecYaml | include "inject-yaml" | nindent 4 }}
{{- end }}
