{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- tuple .Values.serviceAccount.injectYamlMetadata | include "inject-yaml" | nindent 2 }}
{{- tuple .Values.serviceAccount.injectYaml | include "inject-yaml" | nindent 0 }}

{{- if .Values.serviceAccount.role}}
# The cluster role binding if exists
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.serviceAccount.roleBindingKind }}
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}-role-binding
  namespace: {{ include "zairflow-helm.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zairflow-helm.serviceAccountName" . }}
    namespace: {{ include "zairflow-helm.namespace" . }}
roleRef:
  kind: {{ .Values.serviceAccount.roleKind }}
  name: {{ .Values.serviceAccount.role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.serviceAccount.allowKubernetesAccess }}
# Allow kubernetes access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}-access-role
  namespace: {{ include "zairflow-helm.namespace" . }}
rules:
{{ tuple .Values.serviceAccount.allowKubernetesAccessRules | include "inject-yaml" }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}-access-role-binding
  namespace: {{ include "zairflow-helm.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zairflow-helm.serviceAccountName" . }}
    namespace: {{ include "zairflow-helm.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "zairflow-helm.serviceAccountName" . }}-access-role
  apiGroup: rbac.authorization.k8s.io

{{- end -}}

{{- end -}}

