{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}
  namespace: {{ include "zairflow-helm.namespace" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- tuple .Values.serviceAccount.injectYamlMetadata | include "inject-yaml" | nindent 2 }}
{{- tuple .Values.serviceAccount.injectYaml | include "inject-yaml" | nindent 0 }}

# The cluster role binding if exists
{{- if .Values.serviceAccount.roleBinding -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}-role-binding
  namespace: {{ include "zairflow-helm.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zairflow-helm.serviceAccountName" . }}
    namespace: {{ include "zairflow-helm.namespace" . }}
roleRef:
  kind: {{ .Values.serviceAccount.roleBindingKind }}
  name: {{ .Values.serviceAccount.roleBinding }}
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
{{- end -}}

