{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zairflow-helm.serviceAccountName" . }}
  labels:
    {{- include "zairflow-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- tuple .Values.serviceAccount.injectYamlMetadata | include "inject-yaml" | nindent 2 }}
{{- tuple .Values.serviceAccount.injectYaml | include "inject-yaml" | nindent 0 }}
{{- end -}}
