# used limited resources to allow this
# deployment to be tested on local systems.
# Recommended values can be found in README and
# in the values file in this chart.
image:
  tag: local
  pullPolicy: Always

envs:
  # sync to /app
  GIT_AUTOSYNC_REPO_URL: 'https://github.com/LamaAni/zairflow.git'
  # define airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
  AIRFLOW__CORE__LOG_FORMAT: "[%(asctime)s] %(levelname)7s - %(message)s"
  AIRFLOW__CORE__COLORED_LOG_FORMAT: "[%(blue)s%(asctime)s%(reset)s] %(log_color)s%(levelname)7s%(reset)s - %(log_color)s%(message)s%(reset)s"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__CORE__LOGGING_CONFIG_CLASS: "airflow_db_logger.LOGGING_CONFIG"

  # define airflow folders (sync to /app)
  AIRFLOW__CORE__DAGS_FOLDER: /app/experimental/dags
  AIRFLOW__CORE__PLUGINS_FOLDER: /app/experimental/plugins
  
serviceAccount:
  enabled: false
postgres:
  persist: false