#!/usr/bin/env bash

# shellcheck disable=SC1091
CUR_PATH="$SCRIPTS_PATH"
: ${CUR_PATH:="$(realpath $(dirname $(realpath "$BASH_SOURCE[0]")))"}
source "$CUR_PATH/common.sh"

DO_LOAD_ENV=0

case "$1" in
webserver | scheduler | worker | initdb | flower | run)
    # requires prep.
    source "$CUR_PATH/prepare_airflow_env.sh" || exit $?
    ;;
esac

call_airflow "$@" || exit $?
