#!/usr/bin/env bash
CUR_PATH="$DOCKER_BUILD_PATH"
: ${CUR_PATH:="$(realpath $(dirname $(realpath "$BASH_SOURCE[0]")))"}

source "$CUR_PATH/scripts/common.sh"

help_text="
Build the zairflow image
Usage: build
Flags:
    --push   Push to repository.
    -h | --help Show this help menu.
"
DO_PUSH=0
while [ "$#" -gt 0 ]; do
    case $1 in
    --help | -h)
        echo "$help_text"
        exit 0
        ;;
    --push)
        DO_PUSH=1
        ;;
    *)
        echo "Error: unknown argument $1"
        exit 2
        ;;
    esac
    shift
done

CALLING_FOLDER="$PWD"
function change_to_build_path() {
    log:info "Going into build folder @ $CUR_PATH"
    cd "$CUR_PATH"
    assert $? "Failed to change docker build folder @ $CUR_PATH" || exit $?
    return "$@"
}
function change_back_to_calling_folder() {
    log:info "Going back to the calling folder @ $CALLING_FOLDER"
    cd "$CALLING_FOLDER"
    assert $? "Failed to change back to source folder @ $CALLING_FOLDER" || exit $?
    return "$@"
}

function push_tag() {
    log:sep "Tagging and pushing: $1"
    docker tag "$BUILD_NAME:local" "$BUILD_NAME:$1"
    assert $? "Docker tag failed" || return $?
    docker push "$BUILD_NAME:$1"
    assert $? "Docker push failed" || return $?
}

function build_image() {
    source "../envs"
    assert $? "Failed to load envs" || return $?

    log:sep "Building zairflow $ZAIRFLOW_VERSION"
    docker build . -t $BUILD_NAME:local --build-arg "ZAIRFLOW_VERSION=$ZAIRFLOW_VERSION"
    assert $? "Docker build failed" || return $?

    if [ $DO_PUSH -eq 1 ]; then
        push_tag "$ZAIRFLOW_VERSION" || return $?
        push_tag "$ZAIRFLOW_SHORT_VERSION" || return $?
        push_tag "latest" || return $?
    fi
}

change_to_build_path || exit $?
build_image
change_back_to_calling_folder $?
assert $? "Could not build docker image" || exit $?
