apiVersion: v1
kind: ConfigMap
metadata:
  name: zairflow-test-config
data:
  ZAIRFLOW_GIT_AUTOSYNC_URI: 'https://github.com/LamaAni/zairflow.git'
  ZAIRFLOW_DAGS_SUBFOLDER: 'experimental/dags'
  AIRFLOW__CORE__LOGGING_CONFIG_CLASS: airflow_db_logger.airflow_log_config.LOGGING_CONFIG
---
# The main scheduler, runs the init db command
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zairflow-test-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zairflow-test
  template:
    spec:
      containers:
        - name: main
          image: 'lamaani/zairflow:local'
          imagePullPolicy: 'Never'
          env:
            - name: ZAIRFLOW_CONTAINER_TYPE
              value: 'scheduler'
            - name: ZAIRFLOW_RUN_INITDB
              value: 'true'
          envFrom:
            - configMapRef:
                name: zairflow-test-config
          resources:
            limits:
              memory: '1.5Gi'
              cpu: '500m'
---
# the webserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zairflow-test-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zairflow-test
  template:
    spec:
      containers:
        - name: main
          image: 'lamaani/zairflow:local'
          imagePullPolicy: 'Never'
          env:
            - name: ZAIRFLOW_CONTAINER_TYPE
              value: 'webserver'
          envFrom:
            - configMapRef:
                name: zairflow-test-config
          resources:
            limits:
              memory: '1Gi'
              cpu: '200m'
