apiVersion: v1
kind: ConfigMap
metadata:
  name: zaf-tester-cm-env
data:
  ZAIRFLOW_GIT_AUTOSYNC_URI: 'https://github.com/LamaAni/zairflow.git'
  ZAIRFLOW_DAGS_SUBFOLDER: 'experimental/dags'
  AIRFLOW__CORE__LOGGING_CONFIG_CLASS: airflow_db_logger.airflow_log_config.LOGGING_CONFIG