#!/usr/bin/env bash
: ${SCRIPTS_PATH:="$(dirname $(dirname $(realpath "$BASH_SOURCE[0]")))"}
source "$SCRIPTS_PATH/common.sh"

log:sep "Configuring repo and user creds.."
LAST_COMMIT_TEXT="$1"
: ${LAST_COMMIT_TEXT:=$(git log -1 --pretty=%B)}

log:info "Releaseing using commit: $LAST_COMMIT_TEXT"

git config --global user.email "ci@github-action.com"
git config --global user.name "ci automated"
log:info "Updated github user creds"

[ -z $(echo "$LAST_COMMIT_TEXT" | grep -i "\[major\]") ]
ADVANCE_MAJOR="$?"
[ -z $(echo "$LAST_COMMIT_TEXT" | grep -i "\[minor\]") ]
ADVANCE_MINOR="$?"

source "$SCRIPTS_PATH/../envs"
assert $? "Faild to load current version" || exit $?
ZAIRFLOW_OLD_VERSION="$ZAIRFLOW_FULL_VERSION"
ZAIRFLOW_PATCH_VERSION=$((ZAIRFLOW_PATCH_VERSION + 1))
if [ $ADVANCE_MAJOR -eq 1 ]; then
    ZAIRFLOW_MAJOR_VERSION=$((ZAIRFLOW_PATCH_VERSION + 1))
    ZAIRFLOW_MINOR_VERSION=0
fi
if [ $ADVANCE_MINOR -eq 1 ]; then
    ZAIRFLOW_MINOR_VERSION=$((ZAIRFLOW_PATCH_VERSION + 1))
fi

ZAIRFLOW_FULL_VERSION="$ZAIRFLOW_MAJOR_VERSION.$ZAIRFLOW_MINOR_VERSION.$ZAIRFLOW_PATCH_VERSION"
ZAIRFLOW_VERSION="$ZAIRFLOW_MAJOR_VERSION.$ZAIRFLOW_MINOR_VERSION"

log:sep "Updating version $ZAIRFLOW_OLD_VERSION -> $ZAIRFLOW_FULL_VERSION"
rm -f "$SCRIPTS_PATH/../VERSION"
assert "$1" "Failed to remove old version file" || exit $?
echo "$ZAIRFLOW_FULL_VERSION" >"$SCRIPTS_PATH/../VERSION"
assert $? "Failed to update version" || exit $?

log:sep "Commit and push"

git add -A
assert $? "Failed to add current change" || exit $?
git commit -m"Updated version $ZAIRFLOW_OLD_VERSION -> $ZAIRFLOW_FULL_VERSION" -m "[skip ci]"
assert $? "Faild to commit version change" || exit $?
git tag -a "$ZAIRFLOW_FULL_VERSION" -m "[skip ci]"
assert $? "Faild to tag full version" || exit $?
log:info "Tagged and committed, ref:"
git show-ref
assert $? "Faild to show current ref" || exit $?

git push
assert $? "Faild to push changes" || exit $?

log:sep "Version changed."
