#!/bin/bash
curl -Ls "https://raw.githubusercontent.com/LamaAni/zbash-commons/master/install?ts_$(date +%s)=read" | sudo bash || exit $?
source zbash_commons || exit $?

log:info "zbash_commons installed."
