# used limited resources to allow this
# deployment to be tested on local systems.
# Recommended values can be found in README and
# in the values file in this chart.

envs:
  # As an example, initializing without the user code.
  ZAIRFLOW_POST_LOAD_USER_CODE: 'true'

  # Airflow args
  AIRFLOW__CORE__LOAD_EXAMPLES: 'True'

  # Git auto-sync
  GIT_AUTOSYNC_REPO_URL: 'https://github.com/LamaAni/zairflow.git'
  GIT_AUTOSYNC_REPO_BRANCH: new_image

  # COre dags..
  AIRFLOW__CORE__DAGS_FOLDER: '/app/examples/docker-compose/dags'
  AIRFLOW__CORE__PLUGINS_FOLDER: '/app/examples/docker-compose/plugins'

image:
  tag: test_new_image
  pullPolicy: Always

serviceAccount:
  enabled: true

logging:
  useDbLogger: true

executor:
  # type: LocalExecutor
  type: KubernetesExecutor

worker:
  envs:
    - name: MY_TEST_ENV
      value: lama
  resources:
    limits:
      cpu: '1'
      memory: 4Gi
    requests:
      cpu: '500m'
      memory: '1000Mi'