# used limited resources to allow this
# deployment to be tested on local systems.
# Recommended values can be found in README and
# in the values file in this chart.

envs:
  # As an example, initializing without the user code.
  ZAIRFLOW_POST_LOAD_USER_CODE: 'true'

  # Airflow args
  AIRFLOW__CORE__LOAD_EXAMPLES: 'False'

serviceAccount:
  enabled: true

logging:
  useDbLogger: true

executor:
  type: LocalExecutor
