# generate a transient postgres-xl db with username and password. This db will
# NOT be able to withstand restarts.
releases:
  - name: test-zairflow
    # Use of a specific release.
    # chart: https://github.com/[....]/version.tar.gz
    # chart: ../../helm
    chart: https://github.com/LamaAni/zairflow/releases/download/0.3.77/helm.tar.gz
    values:
      - ./airflow_values.yaml