apiVersion: v1
kind: ConfigMap
metadata:
  name: zairflow-test-cm
data:
  # As an example, initializing without the user code.
  ZAIRFLOW_DB_HOST: 'localhost'
  ZAIRFLOW_POST_LOAD_USER_CODE: 'true'

  # Airflow args
  AIRFLOW__CORE__LOGGING_CONFIG_CLASS: airflow_db_logger.LOGGING_CONFIG
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@localhost:5432/airflow'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'False'

  # # uncomment to define the kubernetes executor
  # AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  # AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: latest
  # AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: 'lamaani/zairflow'
  # AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: 'zairflow-test-cm'

---
apiVersion: v1
kind: Pod
metadata:
  name: zairflow-test
  labels:
    name: zairflow-test
spec:
  containers:
    - name: airflow-webserver
      image: 'lamaani/zairflow:latest'
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: '1Gi'
          cpu: '500m'
      env:
        - name: ZAIRFLOW_CONTAINER_TYPE
          value: 'webserver'
        - name: ZAIRFLOW_RUN_INITDB
          value: 'true'
      envFrom:
        - configMapRef:
            name: zairflow-test-cm

    - name: airflow-scheduler
      image: 'lamaani/zairflow:latest'
      resources:
        limits:
          memory: '1.5Gi'
          cpu: '500m'
      env:
        - name: ZAIRFLOW_CONTAINER_TYPE
          value: 'scheduler'
      envFrom:
        - configMapRef:
            name: zairflow-test-cm

    - name: airflow-postgres
      image: 'postgres:12.2'
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_DB
          value: airflow
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: MAX_CONNECTIONS
          value: '10000'
      resources:
        limits:
          memory: '200Mi'
          cpu: '150m'
