#!/usr/bin/env bash
: ${SCRIPTS_PATH:="$(dirname $(realpath "$BASH_SOURCE[0]"))"}
source "$SCRIPTS_PATH/common.sh"

REPO_PATH=$(realpath "$SCRIPTS_PATH/../")
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

type node && type npm && type github-release
assert $? "You must have the following installed: npm, node, npm-github-release (npm package)" || exit $?

[ "$GIT_BRANCH" == "master" ]
assert $? "You must be on master branch to release." || exit $?

help_text="
Build the zairflow image
Usage: release [info]
Flags:
    -h | --help     Show this help menu.
    --stable        A stable release (not pre-release)
    --skip-draft    Skip the draft, release the verison as is.
"

IS_PRERELEASE="true"
IS_DRAFT="true"
COMMENT=""

while [ "$#" -gt 0 ]; do
    case $1 in
    --help | -h)
        echo "$help_text"
        exit 0
        ;;
    --stable)
        IS_PRERELEASE="false"
        ;;
    --skip-draft)
        IS_DRAFT="false"
        ;;
    *)
        if [ -z "$COMMENT" ]; then
            COMMENT="$1"
        else
            echo "Error: unknown argument $1"
            exit 2
        fi
        ;;
    esac
    shift
done

cd "$REPO_PATH"
"$SCRIPTS_PATH/ci/bump_version" "$@"
assert "$?" "Failed to tag version"

source "$REPO_PATH/envs"

RELEASE_NAME="Pre-Release version $ZAIRFLOW_VERSION/$ZAIRFLOW_FULL_VERSION"
if [ "$IS_PRERELEASE" != "true" ]; then
    RELEASE_NAME="Version $ZAIRFLOW_VERSION/$ZAIRFLOW_FULL_VERSION"
fi

log:sep "Updated release - $RELEASE_NAME"
log:info "Done"
