name: 'Build pull request'

on:
  pull_request:
    branches:
      - 'master'
  release:
    branches:
      - 'master'
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cancel previous runs on same branch'
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get commit multi-linux
        id: multi_linux
        run: echo ::set-output enabled=${{contains(/multi-linux)}}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: 'echo Available docker platforms: ${{ steps.buildx.outputs.platforms }}'

      - name: 'Checkout the code'
        uses: actions/checkout@v2

      - name: 'Load docker build cache'
        uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{github.repository}}-${{github.head_ref || github.ref}}
          restore-keys: |
            ${{github.repository}}

      - name: 'Build the Docker image on branch'
        env:
          DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
          DOCKER_ACCESS_TOKEN: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
          DOCKER_IMAGE_TAG: 'ci-build'
        run: bash docker/build

      # Only happens on release.
      - name: 'Release: Get the release tag (version)'
        if: ${{github.event_name == 'release'}}
        id: release_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: 'Release: Push the docker image for release'
        if: ${{github.event_name == 'release'}}
        id: build-docker-image
        env:
          DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
          DOCKER_ACCESS_TOKEN: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
          DOCKER_IMAGE_TAG: 'ci-build'
          DOCKER_VERSION_TAG: 'latest ${{ steps.release_tag.outputs.TAG }}'
        run: bash docker/build --push --skip-build

      - name: 'Release: Create helm release (tar the folder)'
        if: ${{github.event_name == 'release'}}
        id: gzip-helm-release
        run: bash scripts/ci/create_helm_release

      - name: 'Release: Upload files'
        if: ${{github.event_name == 'release'}}
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'helm.tar.gz'
          release-tag: ${{ steps.release_tag.outputs.TAG }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
