name: 'Release new version'

on:
  release:
    branches: [master]
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        id: build-docker-image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: bash docker/build --hub-username "$DOCKER_USERNAME" --push --hub-token "$DOCKER_ACCESS_TOKEN"

      - name: Create helm release (tar the folder)
        id: gzip-helm-release
        run: bash scripts/ci/create_helm_release

      - name: Get the release tag (version)
        id: release_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Upload files to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'helm.tar.gz'
          release-tag: ${{ steps.release_tag.outputs.TAG }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
