name: 'Release new version (patch)'

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: bash docker/build
